sudo: required
dist: trusty

language: scala
scala: 2.11.7
jdk: oraclejdk8

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/

before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete

before_install:
  - sudo bash setupDocker.sh

script:
  # We preserve the environment to ensure the CODACY_PROJECT_TOKEN is accessible inside the containers
  - sudo --preserve-env bash test.sh

notifications:
  webhooks:
    secure: "zCcHPv8CH6sFAks5R8zH/gKyixOIwNpN22fjHF56o7tyAXSGEZnBehRAG7YSZRq3/rOa5DN9+7Ore750jcDsc0bBeXbE86p93DBiJP+KbhZfvxImfxyaOsDmap+te0R+MU1DFcM/NNErTcqJeJKgUv++XDj1kNhGSi5TcZY3pCMgPJWzdKL7V5R4eRNChK5Rxe8mH9YMNZQdw+sMT4XsQOXagDT1NccWvQZRtCNAXumiiz7/Fmk9X55IAFu4DQBG38Qu+PV9TExOIzzc2NyYM3MjRAWqFJEVWrYevJdrvnWHCd6Pgv7rSm028VgWzA3BobIFwpT0GlyxSsBa8WzPPjpGH5/zUM3gi6Ni5A/ayJnooPahExJ9wEOgIBnEgrGFt+wBJENKfOWGMVKqmVILZRTZ2A2PA37RiXjDBAzUtb/gcUapcCrHBVGlClFyy0DKf9UCMM0HHPHrPog/2Gb4TNxktKtofAHV7kN5HFjjxdD1OBgvOM9Io2+3lxRGG1VBnoOqr5K+9ju9BClq6bytEYGqs19PZh1Q1pq0bbjIrFVYw4DXKckc55zNEW72snJOum5IltTrM7lUaoQpRiqyK3aeinXyf8nE84shApKYnqqbf/017ZUvSbfQV25c3tD1dEerUHSy9X0/jVNrPbrBxoXllnqujCqKIpsgItRI7uo="
